version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    cooldown:
      default-days: 1
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directories:
      - '/package/'
      - '/tests/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    cooldown:
      default-days: 1
      exclude:
        - 'pnpm'
        - 'appstore-connect-jwt-generator-core'
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      npm:
        patterns:
          - '*'
