allowBuilds:
  esbuild: false
  unrs-resolver: false

enablePrePostScripts: false


blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - ppstore-connect-jwt-generator-core

overrides:
  eslint-import-resolver-typescript: '^4.4.4'
  semver: '>=7'

strictPeerDependencies: false

trustPolicy: no-downgrade
