autoInstallPeers: true

enablePrePostScripts: true

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

strictPeerDependencies: false

# one day
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
 - pnpm
 - appstore-connect-jwt-generator-core
