autoInstallPeers: true

enablePrePostScripts: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - pnpm
  - appstore-connect-jwt-generator-core

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

overrides:
  '@eslint/js@=9.39.0': ^9.39.1
  diff@<8.0.3: '>=8.0.3'
  eslint@=9.39.0: ^9.39.1

strictPeerDependencies: false
