autoInstallPeers: true

enablePrePostScripts: true

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

strictPeerDependencies: false

# one day
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
 - pnpm
 - appstore-connect-jwt-generator-core

overrides:
  '@eslint/js@=9.39.0': "^9.39.1"
  'eslint@=9.39.0': "^9.39.1"
