name: Automatic release
on:
  release:
    types:
      - published

  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: write

jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: setup Node
        uses: actions/setup-node@v3
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          scope       : 'appstore-connect-jwt-generator-clie'
          always-auth : true

      - name: Can Publish
        run : npx can-npm-publish --verbose
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build
        run : pnpm build
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        run : npm publish --access=public
        env :
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}